### ISSUE TITLE
LTL Circuit Compilation

### ISSUE THREAD

**Issue by mvcisback** [mvcisback/py-metric-temporal-logic#11]
Idea: Compile STL to a circuit given a fixed sample rate or sample times ahead of time.

https://arxiv.org/pdf/1210.0574.pdf

**Comment by mvcisback** [comment]
@shromonag thoughts?

**Comment by shromonag** [comment]
I was actually thinking about this, the only issue we will have with respect to this work is that the nodes could take only boolean values. 

So if we were to use it for evaluation, we could only boolean evaluation. Also fixed sample rate is a big assumption to make I think.

What say?
