### ISSUE TITLE
Problems in the README.md?

### ISSUE THREAD

**Issue by xian49930** [mvcisback/py-metric-temporal-logic#214]
Hi,

I have just noticed that there are some problems of the examples in the README.md. Actually the guide is not very clear and needs to be approved, in my opinion.

First, in the section of **Boolean Evaluation**, the outputs I got are:
**_True
1
1
[(0, 1), (0.2, 1), (1, 1), (3, 1), (4, 0)]
False_**

But in the README.md, they were:
**_True
True
False
[(0, True), (0.2, True), (4, False)]
True_**

It is very confusing. Please correct it, thanks!

**Comment by mvcisback** [comment]
Thanks for pointing this out. I will take a look today.

**Comment by mvcisback** [comment]
So the problem is I forgot the `quantitative=False` flag.

**Comment by xian49930** [comment]
> So the problem is I forgot the `quantitative=False` flag.

Thank you for your response. Please update the outputs, so I can double-check it.

**Comment by xian49930** [comment]
> So the problem is I forgot the `quantitative=False` flag.

I have just noticed that you have updated the outputs. But it still seems like the outputs in the comments are not correct. Here are the new outputs I just got based on your updates:

**True
1
True
[<generator object pointwise_sat.<locals>._eval_mtl.<locals>.<genexpr> at 0x7fca8341b6d0>]
False**

These outputs above are not consistent with the commented outputs. Could you give out the reasons? Or please also update the commented outputs in the README.md file. 

Thanks.

**Comment by mvcisback** [comment]
Sorry for the confusion. The latest master branch fixes that bug, but I haven't updated the pypi version. Will do so shortly.

**Comment by mvcisback** [comment]
The latest master version is published as version 0.1.6.

**Comment by mvcisback** [comment]
Seems to be fixed. Please re-open if the problem persists.

**Comment by xian49930** [comment]
Hi,

You should change the example on Section 'Boolean Evaluation' in README.md to:

# Assumes piece wise constant interpolation.
data = {
    'a': [(0, True), (1, False), (3, False)],
    'b': [(0, False), (0.2, True), (4, False)]
}

phi = mtl.parse('F(a | b)')
print(phi(data, quantitative=False))
# output: True

phi = mtl.parse('F(a | b)')
print(phi(data))
# output: **1**

# Note, quantitative parameter defaults to False

# Evaluate at t=3. 
print(phi(data, time=3, quantitative=False))
# output: **True**

# Compute sliding satisifaction.
print(phi(data, time=None, quantitative=False))
# output: **[(0, True), (0.2, True), (1, True), (3, True), (4, False)]**

# Evaluate with discrete time
phi = mtl.parse('X b')
print(phi(data, dt=0.2, quantitative=False))
# output: **False**
