### ISSUE TITLE
sliding satisfaction for boolean evaluation

### ISSUE THREAD

**Issue by sokolsky** [mvcisback/py-metric-temporal-logic#216]
One more issue: something goes wrong when combining sliding satisfaction with boolean.  Here is the example:
d1 = { 'a': [(0,True),(1,True),(3,True),(4,True),(5,False),(6,True)] }
f1 = mtl.parse('~a')
print(f1(d1,quantitative=False))
-> Output: False; this seems fine

print(f1(d1,time=None))
-> Output: [(0, -1), (1, -1), (3, -1), (4, -1), (5, 0), (6, -1)]; The valuation at time 5 seems questionable, but the format is ok

print(f1(d1,time=None,quantitative=False))
-> Output: [<generator object pointwise_sat.\<locals>._eval_mtl.\<locals>.\<genexpr> at 0x7f04ca795308>]; looks like conversion to string is missing a case

Thanks for your help!

**Comment by mvcisback** [comment]
Hi @sokolsky , this is fixed in the latest patch (pointed out by #214). Please update to `0.1.6` or higher.

**Comment by mvcisback** [comment]
Actually, the 0 is a bit concerning. I will into it.

**Comment by mvcisback** [comment]
So having thought about it just now. 

The 0 weirdness from your second test comes from not using the `quantitative=False` flag, but having binary inputs.

Namely, `~a`, results in the value being negated: `x ↦ -x`, but in python,

`-False == 0`.

The `quantitative=False` option maps:

`False ↦ -1` and `True ↦ -1`.

This is admittedly a gotcha, and I should document better.
