### ISSUE TITLE
Negative time signal when using Next

### ISSUE THREAD

**Issue by Gaudeval** [mvcisback/py-metric-temporal-logic#219]
Hi,

I have a question regarding the use of the Next operator (`X`) in `mtl`. It seems that when the (discrete) time starts at 0, the operator might result in negative times and use undefined signal values. 

The following example highlights the issue. The property tries to capture whether `a` is True at time `t` and False in the next `t+1`:
```python
import mtl
d = {"a": [(0, False), (1, True)]}
f = mtl.parse("(a & (X (~a)))")
f(d, time=None, quantitative=False, dt=1) # [(-1, True), (0, False), (1, False)]
assert not f(d, quantitative=False, dt=1)
```

This should not occur with the current inputs. However, the evaluation of the Next operator results in a signal which starts at `-1`, combined with a signal which does not have a value at that timestamp. Am I mistaken in my interpretation of the result I should expect from the operator?

**Comment by mvcisback** [comment]
Merged #220

**Comment by mvcisback** [comment]
So, looking at this again. I believe that internally this is the correct semantics. We assume constant interpolation (even towards positive and negative infinity).

The problem with #220 is that it assumes the signal has a positive start time, which I don't want to enforce.

I just pushed a change that will use the start of the input signal which addresses this without assuming a positive start time.

**Comment by Gaudeval** [comment]
I do prefer your solution as it uses the existing input signal information, which enforces the [positive time constraint](https://github.com/mvcisback/py-metric-temporal-logic/blob/4f883d1565956b556e1b3bbc3ff0e3e38fad4101/mtl/evaluator.py#L20)
