### ISSUE TITLE
Empty or incorrect Until signal if argument start is anterior to output start

### ISSUE THREAD

**Issue by Gaudeval** [mvcisback/py-metric-temporal-logic#221]
Hi,

I have noticed that I would sometimes get an error due to an empty signal during testing. It occurs using the until operator when either operand results in a signal which starts before the expected output start.

The following snippet highlights the issue:
```python
import mtl

x = {
    "ap1": [(0, True), (0.1, True), (0.2, False)],
}

phi = (mtl.parse("(X TRUE W X TRUE)"))
p = phi(x, 0, quantitative=False)
```

Further investigation shows it occurs during the conversion of the `Until` expression value to a signal. The expression returns a single timestamp, value pair: `(-0.1, 1.0)`. The conversion to a signal (see below) ignores the value as it only picks timestamps fitting into `[start:end)` :
```python
def signal(data, start, end, tag=None):
    data = map(lambda x: (x[0], defaultdict(lambda: None, {tag: x[1]})), data)
    return DiscreteSignal(data=data, start=start, end=end)[start:end]
```

**Comment by mvcisback** [comment]
@Gaudeval Thanks for this analysis! Yes, this implementation of Until seems to have some serious bugs in it. (see #217 )

Unfortunately I don't have time to fix for about a month (taking care of new born), but I would be happy to shepherd a PR to fix this!

**Comment by Gaudeval** [comment]
@mvcisback All my congratulations! 

Focus on the important things (your new born). I will look into a PR.

**Comment by mvcisback** [comment]
Merged. Thank you so much :)
