### ISSUE TITLE
Support for fuzzy logic operations

### ISSUE THREAD

**Issue by Gaudeval** [mvcisback/py-metric-temporal-logic#224]
Hi there,

I have experimented with adding support for fuzzy logic primitives into the library, as opposed to the crisp `True`/`False` non-quantitative evaluation. The user can specify a set of connectives to use during the evaluation of a formula, resulting in values in the interval `[0;1]`.

I acknowledge that the changes, fit for my temporary purposes, are quite inelegant and they would require further work to match the design philosphy of the library. I am willing to undertake that work, but it might come with additional questions.  Would such additions be in line with the library scope? Would they be of interest to the library?

The core of the implementation relies on replacing some of the evaluation primitives with parametric calls to different connectives. The connectives are the ones defined in [Fuzzy Time in Linear Temporal Logic](https://dl.acm.org/doi/10.1145/2629606) [[pdf]](https://re.public.polimi.it/retrieve/handle/11311/1063814/471503/Fuzzy%20Time%20in%20Linear%20Temporal%20Logic_11311-1063814_Frigeri.pdf).

Note that fuzzy-time primitives (e.g. *almost always*) are out of the scope of the work, but they could be considered.

**Comment by mvcisback** [comment]
Hi @Gaudeval,

I'm more than happy to take a look. From my side, this library has mostly been in maintenance mode, but I think having more contributors/maintainers is more than welcome.

I won't be able to properly look into Fuzzy Time operators until after US Thanksgiving, but am more than happy to try and see if this could fit in.

All that said, I am happy to shepherd a PR, assuming it doesn't add too much complication to the existing codebase.

**Comment by Gaudeval** [comment]
Hi @mvcisback,

That sounds great. I will prepare a draft PR to discuss the changes. I understand the library is in maintenance mode and this is an addition outside the initial scope.

**Comment by mvcisback** [comment]
Hi @Gaudeval,

Sorry this took a lot longer to get to than I was expecting.

Thinking about this more, I think that the fuzzy logic increases the scope of the project a bit more than I'm willing to support. If you don't mind, I think let's stick to the forked version you have on pypi. Feel free to open a PR to add a pointer to your fork in the repo.
