### ISSUE TITLE
Breach encoding compatability

### ISSUE THREAD

**Issue by mvcisback** [mvcisback/py-metric-temporal-logic#3]
Input:

    Support for parsing breach like syntax: either by extending current parser or using another parser

Output

    Support outputing breach compatible syntax: alternative to __repr__ encoding

**Comment by slivingston** [comment]
is someone working on this? if not, I can and propose changes in a pull request.

**Comment by mvcisback** [comment]
@slivingston as far as I know, nobody is working on this.

I will be changing the API slightly over the next few days, but the actual AST structure should remain the same.
